server:
  port: 9000

spring:
  application:
    name: "cards"
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/cardssdb
    username: root
    password: root

  jpa:
   # database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
